### ISSUE TITLE
Can`t activate theme on Mac

### ISSUE THREAD

**Issue by thisisElisabeth** [ChiragRupani/blue-moon-theme#1]
Hi, unfortunatly I can´t activate your great theme on mac.

**Comment by ChiragRupani** [comment]
Are you getting any errors while setting theme?

Please check in settings following is set:
`  "workbench.colorTheme": "Blue Moon theme" `

Also, please check if you have auto detect color scheme enabled

https://code.visualstudio.com/docs/getstarted/themes#_automatically-switch-based-on-os-color-scheme. Then you have to select multiple themes and set it to "Blue Moon theme" from below:
![image](https://github.com/user-attachments/assets/8691eea7-6143-4470-8396-60b8b732b7ed)

**Comment by ChiragRupani** [comment]
Hi, I have published new version by removing spaces in file name, that might be causing issue on Mac OS. Could you please try to install latest version and let me know if you are still facing the issue

**Comment by thisisElisabeth** [comment]
Hi,
I got an error message in my workbench settings:
"The design is unknown or not installed."
<img width="580" alt="Bildschirmfoto 2024-10-05 um 12 35 27" src="https://github.com/user-attachments/assets/c6483714-2c7f-4676-9dab-01541462098a">

**Comment by ChiragRupani** [comment]
Looks like it's not finding extension. Could you try installing / updating again - the new version v0.0.6.

**Comment by thisisElisabeth** [comment]
I updated now to the newest version. It is not working. 
<img width="770" alt="Bildschirmfoto 2024-10-05 um 12 52 54" src="https://github.com/user-attachments/assets/82f18a5a-a53e-4c68-a040-4f61ea73621f">

**Comment by ChiragRupani** [comment]
Thanks for your reply. Are you able to see "Blue Moon theme" in the list when you click `cmd + space` in double quotes in workbench.colorTheme in settings.json. I am just wondering if it due to the theme name casing.

![image](https://github.com/user-attachments/assets/9e47f276-623b-43f7-9832-4c85578611b4)

**Comment by thisisElisabeth** [comment]
yes.
<img width="618" alt="Bildschirmfoto 2024-10-05 um 13 56 28" src="https://github.com/user-attachments/assets/e51c9953-06b2-454b-b91f-ac8efdfae9d2">

**Comment by ChiragRupani** [comment]
Looks it is working then, as the selected color is coming from theme only

**Comment by thisisElisabeth** [comment]
I don´t know what exactly that means. I can not see the colors of your theme.

**Comment by ChiragRupani** [comment]
The status bar color and selection color is blue as in below screenshot:
![image](https://github.com/user-attachments/assets/c51c3a6a-1a04-46ed-a457-18d23ed301a3)

It is already applied. The color might be little different on your machine. You can verify by changing to different theme and back to Blue Moon theme

**Comment by thisisElisabeth** [comment]
ok, so in my case it looks like "Default Dark". :-(

**Comment by ChiragRupani** [comment]
For me, it appears from your screenshot, theme is applied correctly. The Default Dark is grayish in color.

Thanks for your all replies. However, I don't think I can do anything further, so closing the issue.
